# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad39311c82989532bf118b0620305fbd734a73b94ca25eddba72be0157df6763a823c61d641a2d57cbe5ed3df32dfff101e91e47c0ad0a45359bfdcb8acb249d

test:
  secret_key_base: 455c0c105cb9a85bdb96c1e7a3bce9c746b69254535fadfb37db941f029fdbda356ebeed800f0a5da5b79b67c6ed45493ddec46d05cf233ab1a4f31dca112e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
